# Generated by Django 4.2.5 on 2023-10-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signupgnomies', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_holder_firstname', models.CharField(max_length=52)),
                ('slot_holder_lastname', models.CharField(max_length=52)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='signupgnomies.category')),
            ],
        ),
    ]
