# Generated by Django 4.2.5 on 2023-10-18 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signupgnomies', '0003_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fills',
            field=models.ManyToManyField(related_name='slot', to=settings.AUTH_USER_MODEL),
        ),
    ]
