# Generated by Django 4.2.5 on 2023-10-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupgnomies', '0004_category_fills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='fills',
        ),
        migrations.AddField(
            model_name='category',
            name='number_of_slots',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
